### ISSUE TITLE
Obsolete description in dropdown page.

### ISSUE THREAD

**Issue by PatrykSzwer** [StarcounterApps/KitchenSink#126]
I think entire case on that page with polymer value binding and using juicy-select as workaround is obsolete, because issue that is described never occur. This part was written year ago, and probably value binding in polymer was fixed since then. If someone knew for sure if It's obsolete, please confirm.

### Screenshot
![image](https://cloud.githubusercontent.com/assets/25042256/25698055/a99d85d4-30bd-11e7-946f-0bf3b5efc9ed.png)

**Comment by warpech** [comment]
@miyconst, @tomalec do you remember if that description is still valid?

Blame shows that was written by @aloscha and probably was true at the time.

**Comment by tomalec** [comment]
I don't :| but it would probably require another check after Polymer 2.0 migration

**Comment by warpech** [comment]
The original reason for creating `juicy-select` is well explained by @miyconst in https://github.com/juicy/juicy-select:

1. The point about IE11 is no longer relevant to us, because we don't support that browser.
2. The point about the initial value seems to be still valid. This is what I see:

![2017-05-05 14_52_40-kitchensink](https://cloud.githubusercontent.com/assets/566463/25746179/8b3a05d2-31a2-11e7-97e2-218908d1a5b7.png)

**Comment by warpech** [comment]
I think that the text on this page should be rewritten to explain better what is meant here. @PatrykSzwer could you propose that in a PR, based on the info above?

**Comment by PatrykSzwer** [comment]
Actually, that initial value is hard-coded. Into DropdownPage.html I found:
`<select slot="kitchensink/dropdown-objects-select" class="kitchensink-select kitchensink-test-product-select" value="{{model.SelectedProductKey$::change}}">
            <option></option>
            <template is="dom-repeat" items="{{model.Products}}">
                <option value="{{item.Key}}">{{item.Name}}</option>
            </template>
        </select>`

that `<option></option>` does the trick. When I remove it:
![image](https://cloud.githubusercontent.com/assets/25042256/25746468/ef7f8656-31a3-11e7-9186-a3dbfb3dc506.png)

So I don't think that description is about that.

**Comment by warpech** [comment]
If you remove the first empty option then still it looks wrong:

![2017-05-05 14_52_40-kitchensink](https://cloud.githubusercontent.com/assets/566463/25746758/2771cadc-31a5-11e7-8851-a356fae1bad0.png)

If it worked ok, you would see "Starcounter Database" rendered in both dropdowns, because the initial value of `SelectedProductKey$` is `CL`.

**Comment by warpech** [comment]
If you remove the first empty option then still it looks wrong:

![2017-05-05 15_11_34-kitchensink](https://cloud.githubusercontent.com/assets/566463/25746804/55eb270a-31a5-11e7-9d3f-ce18d22489f7.png)

If it worked ok, you would see "Starcounter Database" rendered in both dropdowns, because the initial value of `SelectedProductKey$` is `CL`.

**Comment by warpech** [comment]
If you remove the first empty option then it still looks wrong:

![2017-05-05 15_11_34-kitchensink](https://cloud.githubusercontent.com/assets/566463/25746804/55eb270a-31a5-11e7-9d3f-ce18d22489f7.png)

If it worked ok, you would see "Starcounter Database" rendered in both dropdowns, because the initial value of `SelectedProductKey$` is the key of "Starcounter Database"

**Comment by PatrykSzwer** [comment]
Yes, You're right. That <option></option> think could be a (intensional or not) workaround for that. I'll check this and see If I can fix this to work without that empty space and with proper initial options.

**Comment by PatrykSzwer** [comment]
As a reference to conversation with @warpech about this issue, I've changed description above select element to one from juicy-select readme. It will help prevent miss understandings like one that base description was giving.

**Comment by PatrykSzwer** [comment]
Changes were made. Closing.
